### ISSUE TITLE
有大佬知道为什么跑第四个例子时候，运行online_demo和fast-lio2,再play bag包时候出现process has died [pid 229204, exit code -11,进程崩了

### ISSUE THREAD

**Issue by wangxinchengg** [hku-mars/STD#31]
有大佬知道为什么跑第四个例子时候，运行online_demo和fast-lio2,再play bag包时候出现process has died [pid 229204, exit code -11,进程崩了

**Comment by 123456zhi** [comment]
> 有大佬知道为什么跑第四个例子时候，运行online_demo和fast-lio2,再play bag包时候出现process has died [pid 229204, exit code -11,进程崩了

https://blog.csdn.net/lalsd/article/details/121916119
你看一下这篇，可以解决

**Comment by wangxinchengg** [comment]
还是不行

**Comment by 123456zhi** [comment]
> 还是不行
我报错的紧挨着的上面是这个信息，你可以看看你的是什么，搜一下
 error while loading shared libraries: libmetis.so: cannot open shared object file: No such file or directory

**Comment by PanWenbo** [comment]
我是运行rosbag play building_slower_motion_avia.bag后，在运行demo_online.launch的终端报以下错误，有大佬知道怎么解决吗？
[online_demo-2] process has died [pid 6661, exit code -11, cmd /home/panwb/STD/ws/devel/lib/std_detector/online_demo __name:=online_demo __log:=/home/panwb/.ros/log/a396bff2-0086-11ef-b673-e77abc427f92/online_demo-2.log].
log file: /home/panwb/.ros/log/a396bff2-0086-11ef-b673-e77abc427f92/online_demo-2*.log

**Comment by rmt000901** [comment]
请问你解决了吗

**Comment by maomao0220** [comment]
请问你解决了吗？ @PanWenbo

**Comment by PanWenbo** [comment]
还没有解决，若是解决了我们都分享下经验

**Comment by maomao0220** [comment]
重新装了一遍gtsam，解决

**Comment by rmt000901** [comment]
> 重新装了一遍gtsam，解决

什么版本的呀

**Comment by maomao0220** [comment]
我装的4.1.1

**Comment by PanWenbo** [comment]
我装的gtsam-4.0.3,采用以下方法解决的
https://blog.csdn.net/weixin_40324045/article/details/121284253

**Comment by rmt000901** [comment]
> 我装的gtsam-4.0.3,采用以下方法解决的 https://blog.csdn.net/weixin_40324045/article/details/121284253

请问您参照这篇文章中的什么了呀，我试了一下还是报错

**Comment by rmt000901** [comment]
> 重新装了一遍gtsam，解决

重装了几遍还是不行啊

**Comment by PanWenbo** [comment]
如果要运行LIO-SAM还要加上-DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF，也就是：
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_WITH_EIGEN_MKL=OFF -DGTSAM_WITH_EIGEN_MKL_OPENMP=OFF ..

**Comment by Dumb6** [comment]
还是没有解决@PanWenbo 您是重新安装库解决的么

**Comment by TerryLSR** [comment]
本人ubuntu20.04，在运行第四个例子时也会挂死，排查有两个原因
1. eigen版本对应的写法问题，在 pose_vec.push_back(pose) 的时候挂死；eigen的官方说明，虽然cmakelist指定了c++14，但确实是此处挂死问题
![image](https://github.com/user-attachments/assets/3c1ea4ad-dcd2-467f-b5d4-a236144efbce)

将对应的定义和函数修改即可
  std::vector<Eigen::Affine3d, Eigen::aligned_allocator<Eigen::Affine3d> > pose_vec;
  std::vector<Eigen::Affine3d, Eigen::aligned_allocator<Eigen::Affine3d> > origin_pose_vec;
  std::vector<Eigen::Affine3d, Eigen::aligned_allocator<Eigen::Affine3d> > key_pose_vec;

2.gtsam在update函数挂死，怀疑是编译库4.1.1时开启了某些配置（严重怀疑是tbb）。在用cmake编译安装gtsam时，使用下述命令即可
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_WITH_EIGEN_MKL=OFF -DGTSAM_WITH_EIGEN_MKL_OPENMP=OFF -DGTSAM_WITH_TBB=OFF ..

**Comment by PixelVoyager-30** [comment]
> 本人ubuntu20.04，在运行第四个例子时也会挂死，排查有两个原因
> 
> 1. eigen版本对应的写法问题，在 pose_vec.push_back(pose) 的时候挂死；eigen的官方说明，虽然cmakelist指定了c++14，但确实是此处挂死问题
>    ![image](https://github.com/user-attachments/assets/3c1ea4ad-dcd2-467f-b5d4-a236144efbce)
> 
> 将对应的定义和函数修改即可 std::vector<Eigen::Affine3d, Eigen::aligned_allocatorEigen::Affine3d > pose_vec; std::vector<Eigen::Affine3d, Eigen::aligned_allocatorEigen::Affine3d > origin_pose_vec; std::vector<Eigen::Affine3d, Eigen::aligned_allocatorEigen::Affine3d > key_pose_vec;
> 
> 2.gtsam在update函数挂死，怀疑是编译库4.1.1时开启了某些配置（严重怀疑是tbb）。在用cmake编译安装gtsam时，使用下述命令即可 cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_WITH_EIGEN_MKL=OFF -DGTSAM_WITH_EIGEN_MKL_OPENMP=OFF -DGTSAM_WITH_TBB=OFF ..

变量定义少打了个符号，应该是 `std::vector<Eigen::Affine3d, Eigen::aligned_allocator<Eigen::Affine3d>> pose_vec;`

**Comment by PixelVoyager-30** [comment]
我运行第四个例子也是两个问题，第一个通过参考上面已经解决；第二个是gtsam优化的问题，gdb定位代码 `isam.update(graph, initial);` 无论我禁用TBB或者编译的时候指定使用系统的Eigen库，还是报同样的错误
```bash
0  __GI___libc_free (mem=0x51) at malloc.c:3102
#1  0x00005930776c0309 in Eigen::internal::handmade_aligned_free (ptr=0x5930a1b9a5f0)
    at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:98
#2  0x00005930776c0371 in Eigen::internal::aligned_free (ptr=0x5930a1b9a5f0)
    at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:179
#3  0x00005930776c6579 in Eigen::internal::conditional_aligned_free<true> (
    ptr=0x5930a1b9a5f0) at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:230
#4  0x00005930776d1409 in Eigen::internal::conditional_aligned_delete_auto<double, true> (
    ptr=0x5930a1b9a5f0, size=6) at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:416
#5  0x00005930776c6b8f in Eigen::DenseStorage<double, -1, -1, 1, 0>::~DenseStorage (
    this=0x5930a1bbc018, __in_chrg=<optimized out>)
    at /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:542
#6  0x00005930776c173e in Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::~PlainObjectBase (this=0x5930a1bbc018, __in_chrg=<optimized out>)
    at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:98
#7  0x00005930776c175e in Eigen::Matrix<double, -1, 1, 0, -1, 1>::~Matrix (
    this=0x5930a1bbc018, __in_chrg=<optimized out>)
    at /usr/include/eigen3/Eigen/src/Core/Matrix.h:178
#8  0x00005930776fbe32 in std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> >::~pair (this=0x5930a1bbc010, __in_chrg=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/9/bits/stl_pair.h:208
#9  0x00005930776fbe56 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > >::destroy<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > (this=0x7ffd17728aa0, __p=0x5930a1bbc010)
    at /usr/include/c++/9/ext/new_allocator.h:152
#10 0x00005930776f2665 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > > >::destroy<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > (__a=..., __p=0x5930a1bbc010)
    at /usr/include/c++/9/bits/alloc_traits.h:496
#11 0x00005930776e921d in std::_Rb_tree<unsigned long, std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> >, std::_Select1st<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > >::_M_destroy_node (
    this=0x7ffd17728aa0, __p=0x5930a1bbbff0) at /usr/include/c++/9/bits/stl_tree.h:642
#12 0x00005930776dd19f in std::_Rb_tree<unsigned long, std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> >, std::_Select1st<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > >::_M_drop_node (
    this=0x7ffd17728aa0, __p=0x5930a1bbbff0) at /usr/include/c++/9/bits/stl_tree.h:650
#13 0x00005930776d2278 in std::_Rb_tree<unsigned long, std::pair<unsigned long const, Eigen--Type <RET> for more, q to quit, c to continue without paging--
::Matrix<double, -1, 1, 0, -1, 1> >, std::_Select1st<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > >::_M_erase (
    this=0x7ffd17728aa0, __x=0x5930a1bbbff0) at /usr/include/c++/9/bits/stl_tree.h:1920
#14 0x0000795345574fae in gtsam::ISAM2::addVariables(gtsam::Values const&, gtsam::ISAM2Result::DetailedResults*) () from /usr/local/lib/libgtsam.so.4
#15 0x00007953455795b2 in gtsam::ISAM2::update(gtsam::NonlinearFactorGraph const&, gtsam::Values const&, gtsam::ISAM2UpdateParams const&) () from /usr/local/lib/libgtsam.so.4
#16 0x0000795345578c62 in gtsam::ISAM2::update(gtsam::NonlinearFactorGraph const&, gtsam::Values const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, boost::optional<gtsam::FastMap<unsigned long, int> > const&, boost::optional<gtsam::FastList<unsigned long> > const&, boost::optional<gtsam::FastList<unsigned long> > const&, bool) ()
   from /usr/local/lib/libgtsam.so.4
#17 0x00005930776bddd1 in main (argc=1, argv=0x7ffd1772a698)
    at /home/docker/std_ws/src/STD-master/demo/online_demo.cpp:435

```
